# Generated by Django 4.2.1 on 2023-06-07 04:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startup', '0003_auto_20230606_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('stage', models.CharField(choices=[('seed', 'Seed Round'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('pre_ipo', 'Pre-IPO')], max_length=10)),
                ('audience', models.BigIntegerField()),
                ('raised_amount', models.BigIntegerField()),
                ('pitch_title', models.CharField(max_length=5000)),
                ('business_description', models.CharField(max_length=10000)),
                ('company_highlights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('team', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical company',
                'verbose_name_plural': 'historical companys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('stage', models.CharField(choices=[('seed', 'Seed Round'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('pre_ipo', 'Pre-IPO')], max_length=10)),
                ('audience', models.BigIntegerField()),
                ('raised_amount', models.BigIntegerField()),
                ('pitch_title', models.CharField(max_length=5000)),
                ('business_description', models.CharField(max_length=10000)),
                ('company_highlights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('team', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('industry', models.ManyToManyField(to='startup.industry')),
            ],
        ),
    ]
