# Generated by Django 4.2.1 on 2023-06-16 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startup', '0005_remove_company_team_remove_historicalcompany_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='founder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='step_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='step_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='step_two',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='founder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='step_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='step_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='step_two',
            field=models.BooleanField(default=False),
        ),
    ]
