# Generated by Django 4.2.1 on 2023-06-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0007_historicalteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalteam',
            name='company',
        ),
        migrations.RemoveField(
            model_name='team',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='team',
            field=models.ManyToManyField(related_name='companies', to='startup.team'),
        ),
    ]
