# Generated by Django 4.2.1 on 2023-06-18 06:24

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startup', '0010_remove_company_team_historicalteam_founder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_highlights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ManyToManyField(blank=True, null=True, to='startup.industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='raised_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='stage',
            field=models.CharField(blank=True, choices=[('seed', 'Seed Round'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('pre_ipo', 'Pre-IPO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='company_highlights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='raised_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='stage',
            field=models.CharField(blank=True, choices=[('seed', 'Seed Round'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('pre_ipo', 'Pre-IPO')], max_length=10, null=True),
        ),
    ]
