# Generated by Django 4.2.1 on 2023-06-18 19:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0011_alter_company_company_highlights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='company/cover_photos'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='pitch',
            field=models.FileField(blank=True, null=True, upload_to='company/pitches'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pitch_video',
            field=models.FileField(blank=True, null=True, upload_to='company/pitch_videos'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='cover_photo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='pitch',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='pitch_video',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
