# Generated by Django 4.2.1 on 2023-06-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0012_alter_company_cover_photo_alter_company_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='company/cover_photos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pitch',
            field=models.FileField(blank=True, null=True, upload_to='company/pitches/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pitch_video',
            field=models.FileField(blank=True, null=True, upload_to='company/pitch_videos/'),
        ),
    ]
