# Generated by Django 4.2.1 on 2023-06-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0014_alter_company_cover_photo_alter_company_pitch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ManyToManyField(to='startup.industry'),
        ),
    ]
