# Generated by Django 4.2.1 on 2023-06-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0015_alter_company_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to='startup/company/cover_photos/'),
        ),
    ]
