# Generated by Django 4.2.1 on 2023-06-18 23:16

from django.db import migrations, models
import startup.models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0016_alter_company_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to=startup.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='company',
            name='pitch',
            field=models.FileField(blank=True, null=True, upload_to=startup.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='company',
            name='pitch_video',
            field=models.FileField(blank=True, null=True, upload_to=startup.models.generate_unique_filename),
        ),
    ]
