# Generated by Django 4.2.1 on 2023-06-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0018_alter_company_cover_photo_alter_company_pitch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='valuation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='valuation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
