# Generated by Django 4.2.1 on 2023-06-21 03:18

from django.db import migrations, models
import startup.models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0020_remove_company_nda_remove_historicalcompany_nda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='signed_nda',
            field=models.FileField(blank=True, null=True, upload_to=startup.models.generate_signed_nda_filename),
        ),
        migrations.AlterField(
            model_name='company',
            name='unsigned_nda',
            field=models.FileField(blank=True, null=True, upload_to=startup.models.generate_unsigned_nda_filename),
        ),
    ]
