# Generated by Django 4.2.1 on 2023-05-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_historicaluser'),
    ]

    operations = [
    ]
