# Generated by Django 4.2.1 on 2023-05-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230519_1845'),
    ]

    operations = [
    ]
