# Generated by Django 4.2.1 on 2023-05-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230519_1907'),
    ]

    operations = [
    ]
