# Generated by Django 4.2.1 on 2023-05-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230519_1912'),
    ]

    operations = [
    ]
