# Generated by Django 4.2.1 on 2023-05-19 23:18

from django.db import migrations

from user.models import User
from django.contrib.auth.models import Group


def create_user_groups(apps, schema_editor):

    # Create your user groups here

    admin_group, _ = Group.objects.get_or_create(name='Admin')
    investors_group, _ = Group.objects.get_or_create(name='Investor')
    startups_group, _ = Group.objects.get_or_create(name='Startup')

    users = User.objects.filter(is_superuser=False, is_staff=False)
    for user in users:
        if user.is_superuser or user.is_staff :
            user.groups.add(admin_group)


def revert_user_groups(apps, schema_editor):

    Group = apps.get_model('user', User.groups)

    # Reverse the group creation here
    Group.objects.filter(name__in=['Admin', 'Investors', 'Startups']).delete()
    # Delete additional groups as needed

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20230519_1915'),
    ]

    operations = [
        migrations.RunPython(create_user_groups,)
    ]
