# Generated by Django 4.2.1 on 2023-05-28 19:42

from django.db import migrations

def insert_initial_data(apps, schema_editor):
    SubGroup = apps.get_model('user', 'SubGroup')
    # Create and save the initial data objects
    subgroups = [
        SubGroup(name='Admin', group_id=1),
        SubGroup(name='Admin', group_id=2),
        SubGroup(name='Admin', group_id=3),
        # Add more initial data objects as needed
    ]
    for subgroup in subgroups:
        subgroup.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_historicalsubgroup'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data),
    ]
