# Generated by Django 4.2.1 on 2023-05-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20230528_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='HistoricalSubGroup',
        ),
        migrations.DeleteModel(
            name='SubGroup',
        ),
    ]
